config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'
  get 'products/index'
#  get 'sessions/new'
#  get 'users/new'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/menus', to: 'static_pages#menus'
  get '/contact', to: 'static_pages#contact'
  get '/dukkah', to: 'static_pages#dukkah'
  get '/farro', to: 'static_pages#farro'
  get '/shrimp', to: 'static_pages#shrimp'
  get '/pasta', to: 'static_pages#pasta'
  get '/noodle', to: 'static_pages#noodle'
  get '/lentils', to: 'static_pages#lentils'
  get '/schnitzel', to: 'static_pages#schnitzel'
  get '/jalapeno', to: 'static_pages#jalapeno'
  get '/sample', to: 'products#sample'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/mealselect', to: 'products#index'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
    
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
    
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    validates :firstName, presence:true, length: {maximum:50}
    validates :lastName, presence:true, length: {maximum:50}
    validates :address1, presence:true, length: {maximum:50}
    validates :town, presence:true, length: {maximum:50}
    validates :eircode, presence:true, length: {maximum:10}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence:true, length: {maximum: 255},format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence:true, length:{minimum:6}, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
      @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  
  before_action :logged_in_user    
    
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
    
  # Confirms a logged-in user.
    def logged_in_user
        unless logged_in?
            flash[:danger] = "Please log in."
            redirect_to login_url
        end
    end    
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
    def sample
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          log_in user
          redirect_to user
      else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
      end
  end
    
  def destroy
      log_out
      redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menus
  end
  
  def contact
  end
    
  def register
  end
    
  def dukkah
  end
    
  def farro
  end

  def shrimp 
  end
    
  def pasta
  end
 
  def noodle
  end

  def lentils
  end

  def schnitzel 
  end

  def jalapeno
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
    
  def show
      @user = User.find(params[:id])
  end
    
  def new
      @user = User.new
  end
    
  def create
      @user = User.new(user_params)
      if @user.save
          log_in @user
          flash[:success] = "Welcome to Foodie.ie"
          redirect_to @user
      else
          render 'new'
      end
  end
    
  def edit
      @user = User.find(params[:id])
  end
    
  def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
          flash[:success] = "Profile updated"
          redirect_to @user
      else
          render 'edit'
      end
  end
    
  private
    def user_params
        params.require(:user).permit(:firstName, :lastName, :address1, :address2, :town, :eircode, :email, :password, :password_confirmation)
    end
    
    # Before filters
    
    
    # Confirms a logged-in user.
    def logged_in_user
        unless logged_in?
            flash[:danger] = "Please log in."
            redirect_to login_url
        end
    end
    
    # Confirms the correct user
    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #Logs in the given user
    def log_in(user)
        session[:user_id] = user.id
    end
    
    #Returns the current logged-in user (if any).
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    
    #Returns true if the user is logged in, false otherwise
    def logged_in?
       !current_user.nil? 
    end
    
    #Logs out the current user
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodie</title>
    <link rel="stylesheet" href="/assets/ionicons.css" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,200,300,400" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header> 
        <nav>
            <div class="container">
                <ul class="main-nav">
                    <li><%= link_to "Home", home_path %></li>
                    <li><%= link_to "Meals", menus_path %></li>
                    <li><a href="/home#contact">Contact</a></li>
                    <% if logged_in? %>
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= link_to "Log out", logout_path, method: :delete %></li>
                    <% else %>
                        <li><%= link_to "Log In", login_path %></li>
                    <% end %>
                </ul>
            </div>
            
        </nav>
        
        <%= yield %>
    <footer>
        <div class="container">
            <p>Copyright &copy; 2018 by Foodie.ie. All rights reserved.</p>
        </div>
    </footer>
        
  </body>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/static_pages/dukkah.html.erb
<br><br>
<div class="container meals-background">
    <div class = "col span1-of-4 box">
        <figure class="tape-photo">
            <img src="/assets/img/menu1.jpg" alt="meal photo"> 
        </figure>
        <div class="photo-caption">
            <p class>Dukkah-Spiced Beef &amp; Couscous</p>
        </div>
        <div class="mybtn-order">
            <%= link_to "Order", mealselect_path, class: "mybtn mybtn-full mybtn-large" %>
        </div>
    </div>
    <div class="col span-1-of-4">
    </div>
    <div class="col span-2-of-4">
        <div class="meals-details">
            <b><p>Price: $9.99</p></b>
            <p>Time: 20mins</p>
            <p>Nutrition: 760 calories</p>
            <p>Servings: 2</p>
            <p>This quick-cooking recipe features vibrant dukkah (an Egyptian-style blend of herbs and spices), which lends warming spice to thin slices of beef. It provides delightful contrast to our side of fluffy couscous studded with sweet golden raisins.</p>
        </div>
        <br>
        <div class="ingredients">
            <h3><b>Ingredients</b></h3>
            <p>10 oz Thinly Sliced Beef</p>
            <p>½ cup Yellow Couscous</p>
            <p>2 cloves Garlic</p>
            <p>1 bunch Kale</p>
            <p>Tbsps Crème Fraîche</p> 
            <p>2 Tbsps Tahini</p>
            <p>1 Tbsp Red Wine Vinegar</p>
            <p>1½ Tbsps  Golden Raisins</p>
            <p>1 Tbsp  Dukkah Seasoning (Za'atar, Ground Coriander, Ground Fennel Seeds, Ground Cumin, &amp; Black Sesame Seeds)</p>
        </div>
        <br>
        <div class="instructions">
            <h3><b>Instructions</b></h3>
            <ol>
               <li>In a small saucepan, combine the couscous, raisins, and 3/4 cup of water; season with salt and pepper. Heat to boiling on high. Once boiling, turn off the heat. Cover and let stand 6 to 8 minutes, or until the water has been absorbed and the couscous is tender. Fluff with a fork. Drizzle with olive oil and season with salt and pepper; stir to combine. Cover to keep warm. </li>
               <br>
               <li>While the couscous cooks, wash and dry the kale. Separate the kale leaves from the stems; discard the stems, then roughly chop the leaves. Peel and roughly chop 2 cloves of garlic. </li> 
               <br>
               <li>While the couscous continues to cook, in a large pan (nonstick, if you have one), heat a drizzle of olive oil on medium-high until hot. Add the chopped kale and half the chopped garlic; season with salt and pepper. Cook, stirring occasionally, 3 to 4 minutes, or until slightly wilted. Add 1/4 cup of water (carefully, as the liquid may splatter). Cook, stirring frequently, 2 to 3 minutes, or until the kale is wilted and the water has cooked off. Transfer to a bowl. Taste, then season with salt and pepper if desired. Cover with foil to keep warm. Wipe out the pan.  </li>
               <br>
               <li>Pat the beef dry with paper towels. Season with salt and pepper. In the same pan, heat a drizzle of olive oil on medium-high until hot. Add the seasoned beef in an even layer. Cook, without stirring, 1 to 2 minutes, or until lightly browned. Add half the dukkah (you will have extra) and the remaining chopped garlic. Cook, stirring frequently, 1 to 2 minutes, or until the beef is just cooked through. Turn off the heat. Stir in the crème fraîche. Taste, then season with salt and pepper if desired.</li>
               <br>
               <li>While the beef cooks, in a bowl, whisk together the tahini, vinegar, and 1 tablespoon of olive oil. Slowly whisk in up to 2 tablespoons of water to thin to your desired consistency. Taste, then season with salt and pepper if desired. Serve the cooked beef with the cooked couscous and kale. Top with the dressing. Enjoy!</li>
            </ol>
        </div>
    </div>
</div>

app/views/static_pages/farro.html.erb
<br><br>
<div class="container meals-background">
    <div class = "col span1-of-4 box">
        <figure class="tape-photo">
            <img src="/assets/img/menu2.jpg" alt="meal photo">
        </figure>
        <div class="photo-caption">
            <p class>Chicken over Farro Salad</p>
        </div>
        <div class="mybtn-order">
            <%= link_to "Order", mealselect_path, class: "mybtn mybtn-full mybtn-large" %>
        </div>
    </div>
    <div class="col span-1-of-4">
    </div>
    <div class="col span-2-of-4">
        <div class="meals-details">
            <b><p>Price: $9.99</p></b>
            <p>Time: 25mins</p>
            <p>Nutrition: 690 calories</p>
            <p>Servings: 2</p>
            <p>Cooked alongside nutty farro, saffron—a prized spice originally from North Africa—lends a subtle, aromatic lift to spiced chicken served on top. We’re adding roasted carrots and dates to the farro, which lends balance to the chicken’s bold, Spanish-inspired spices, including paprika, coriander, and cinnamon.</p>
        </div>
        <br>
        <div class="ingredients">
            <h3><b>Ingredients</b></h3>
            <p>2 Boneless, Skinless Chicken Thighs </p>
            <p>½ cup Semi-Pearled Farro</p>
            <p>1 Persian Cucumber</p>
            <p>4oz Grape or Cherry Tomato</p>
            <p>2 cloves Garlic</p> 
            <p>2 Scallions</p>
            <p>2 Dried Turkish Figs</p>
            <p>1/2 cup Plain Greek Yoghurt</p>
            <p>1 Tbsp  Ras El Hanout</p>
            <p>1 Tbsp White Wine Vinegar</p>
        </div>
        <br>
        <div class="instructions">
            <h3><b>Instructions</b></h3>
            <ol>
               <li>If you’re grilling, preheat your grill to maintain a temperature of 450-500°F. Oil the grill grates. Heat a medium pot of salted water to boiling on high. Once boiling, add the farro and cook, uncovered, 18 to 20 minutes, or until tender. Turn off the heat. Drain thoroughly and return to the pot. Cover to keep warm.</li>
               <br>
               <li>While the farro cooks, wash and dry the fresh produce. Small dice the cucumber. If necessary, peel 1 clove of garlic (you may have extra). Roughly chop the garlic; using the flat side of your knife, smash until it resembles a paste (or use a zester). Halve the tomatoes; place in a bowl. Drizzle with olive oil and season with salt and pepper. Stir to coat. Roughly chop the figs. Cut off and discard the root ends of the scallions; thinly slice, separating the white bottoms and green tops. In a bowl, combine the chopped figs, sliced white bottoms of the scallions, and vinegar. </li>
               <br>
               <li>While the farro continues to cook, in a bowl, combine the yogurt, diced cucumber, a drizzle of olive oil, and as much of the garlic paste as you’d like. Season with salt and pepper.</li>
               <br>
               <li>STOVE: Pat the chicken dry with paper towels. Season on both sides with salt, pepper, and enough of the ras el hanout to coat (you may have extra). In a medium pan, heat 2 teaspoons of olive oil on medium-high until hot. Add the seasoned chicken and cook 6 to 7 minutes per side, or until browned and cooked through. Transfer to a plate and loosely cover with aluminum foil to keep warm.
                GRILL: Pat the chicken dry with paper towels. Season on both sides with salt, pepper, and enough of the ras el hanout to coat (you may have extra). Drizzle with olive oil. Grill the seasoned chicken 5 to 6 minutes per side, or until browned and cooked through. Transfer to a plate and loosely cover with aluminum foil to keep warm.</li>
                <br>
                <li>To the pot of cooked farro, add the seasoned tomatoes, rehydrated figs (including any liquid from the bowl), and a drizzle of olive oil. Stir to combine; season with salt and pepper to taste. Serve the cooked chicken over the finished farro salad. Garnish with the sliced green tops of the scallions. Serve with the cucumber-yogurt sauce on the side. Enjoy!
                </li>
            </ol>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
   <div class="hero-text-box">
        <h1>Goodbye food stress. <br> Hello quick &amp; delicious meals.</h1>

        <%= link_to "Sign Up", signup_path, class: "mybtn mybtn-full mybtn-large" %>
        <%= link_to "Meals", menus_path, class: "mybtn mybtn-ghost mybtn-large" %>
    </div>    
</header>

<section class="section-features">
    <div class="container">
        <h2>Get food fast &mdash; not fast food</h2>
        <p class="long-copy">
            Welcome to Foodie.ie, your new premium food delivery service. We know you're always busy. No time for cooking. So let us take care of that. We're really good at it. We promise!
        </p>
    </div>
    <div class="container">
        <div class="col span-1-of-4 box features-box">
            <i></i>
            <h3>Up to 365 days/year</h3>
            <p>Our incredible selection of meals ensures you can choose a different meal every day of the year and still not get through our full menu!</p>
        </div>

        <div class="col span-1-of-4 box features-box">
            <i ></i>
            <h3>Ready in 30 minutes</h3>
            <p>You're only ever thirty minutes away from a delicious and super healthy meal sitting on your table. </p>
        </div>

        <div class="col span-1-of-4 box features-box">
            <i ></i>
            <h3>100% organic</h3>
            <p>All our vegetables are fresh, organic, and local. Animals are raised without added hormones or antibiotics. Good for your health, the environment, and it tastes better!</p>
        </div>

        <div class="col span-1-of-4 box features-box">
            <i ></i>
            <h3>Order anything</h3>
            <p>We don't limit your creativity, which means that once you've signed up, you can order as many or as few meals as you wish. It's entirely up to you!</p>
        </div>
    </div>
</section>

<section class="section-meals"> 
    <ul class="meals-showcase clearfix">
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/1.jpg" alt="Korean egg and veg">
            </figure>
        </li>
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/2.jpg" alt="chicken breast">
            </figure>
        </li>
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/3.jpg" alt="simple pizza">
            </figure>
        </li>
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/4.jpg" alt="pumpkin soup">
            </figure>
        </li>

    </ul>

    <ul class="meals-showcase clearfix">
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/5.jpg" alt="beef">
            </figure>
        </li>
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/6.jpg" alt="baguette">
            </figure>
        </li>
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/7.jpg" alt="burger">
            </figure>
        </li>
        <li>
            <figure class="meal-photo">
                <img src="/assets/img/8.jpg" alt="granola">
            </figure>
        </li>
    </ul>
</section>

<section  class="section-form" id="contact">
    <div >
        <h2>Get in touch</h2>
    </div>

    <div >
        <form method="post" action="#" class="contact-form">
            <div class="container">
                <div class="col span-1-of-3">
                    <label for="name">Name</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="text" name="name" id="name" placeholder="Your name" required>
                </div>
            </div>

            <div class="container">
                <div class="col span-1-of-3">
                    <label for="email">Email</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="email" name="email" id="email" placeholder="name@abc.com" required>
                </div>
            </div>

            <div class="container">
                <div class="col span-1-of-3">
                    <label for="find-us">How did you find us?</label>
                </div>
                <div class="col span-2-of-3">
                    <select name="find-us" id="find-us">
                        <option value="friends">friends</option>
                        <option value="search" selected>search engine</option>
                        <option value="ad">advertisemnt</option>
                        <option value="other-way">some other way</option>   
                    </select>
                </div>
            </div>

            <div class="container">
                <div class="col span-1-of-3">
                  <label>Newsletter</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="checkbox" name="newsletter" id="news" checked> Yes please
                </div>
            </div>

            <div class="container">
                <div class="col span-1-of-3">
                    <label>Drop us a line</label>
                </div>
                <div class="col span-2-of-3">
                    <textarea name="message" placeholder="Your message" > </textarea>
                </div>
            </div>

            <div class="container">
                <div class="col span-1-of-3">
                    <label>&nbsp;</label>
                </div>
                <div class="col span-2-of-3">
                    <input type="submit" value="Send">
                </div>
            </div> 
        </form>
    </div>
</section>

<section class="section-testimonials">
    <div class="container">

        <h2>What our customers say...</h2>
    </div>

    <div class="container">
        <div class="col span-1-of-3">
           <blockquote>Foodie.ie is just brilliant! I just started a new business startup which leaves me with no time for cooking, so Foodie.ie is a life saver. Now that I have gotten used to it, I couldn't live without my daily meals!
            <cite><img src="/assets/img/customer-1.jpg">Phil Duncan</cite>
            </blockquote> 
        </div>

        <div class="col span-1-of-3">
           <blockquote>Inexpensive, healthy, and great tasting ingredients delivered right to my home. Simple to follow instructions. My family and me are so in love with your service. Keep up the great work!
            <cite><img src="/assets/img/customer-2.jpg">Jill Murphy</cite>
            </blockquote> 
        </div>

        <div class="col span-1-of-3">
           <blockquote>I was tired of eating the same old bland meals every evening. I decided to give Foodie.ie a try and haven't looked back. I actually look forward to coming home in the evenings and cooking now!
            <cite><img src="/assets/img/customer-3.jpg">Mark Kelly</cite>
            </blockquote> 
        </div>
    </div>
</section>

app/views/static_pages/jalapeno.html.erb
<br><br>
<div class="container meals-background">
    <div class = "col span1-of-4 box">
        <figure class="tape-photo">
            <img src="/assets/img/menu8.jpg" alt="meal photo">
        </figure>
        <div class="photo-caption">
            <p class>Jalapeno Burgers</p> 
        </div>
        <div class="mybtn-order">
            <%= link_to "Order", mealselect_path, class: "mybtn mybtn-full mybtn-large" %>
        </div>
    </div>
    <div class="col span-1-of-4">
    </div>
    <div class="col span-2-of-4">
        <div class="meals-details">
            <b><p>Price: $9.99</p></b>
            <p>Time: 25mins</p>
            <p>Nutrition: 750 calories</p>
            <p>Servings: 2</p>
            <p>We’re taking the classic cheeseburger to new heights by topping it with an unexpected combination of creamy, tangy goat cheese and spicy-sweet marinated jalapeño. For a flavorful side, we’re roasting carrots with a blend of bold, smoky spices like paprika, ground mustard, and more.</p>
        </div>
        <br>
        <div class="ingredients">
            <h3><b>Ingredients</b></h3>
            <p>10 oz Thinly Sliced Beef</p>
            <p>½ cup Yellow Couscous</p>
            <p>2 cloves Garlic</p>
            <p>1 bunch Kale</p>
            <p>Tbsps Crème Fraîche</p> 
            <p>2 Tbsps Tahini</p>
            <p>1 Tbsp Red Wine Vinegar</p>
            <p>1½ Tbsps  Golden Raisins</p>
            <p>1 Tbsp  Dukkah Seasoning (Za'atar, Ground Coriander, Ground Fennel Seeds, Ground Cumin, &amp; Black Sesame Seeds)</p>
        </div>
        <br>
        <div class="instructions">
            <h3><b>Instructions</b></h3>
            <ol>
               <li>In a small saucepan, combine the couscous, raisins, and 3/4 cup of water; season with salt and pepper. Heat to boiling on high. Once boiling, turn off the heat. Cover and let stand 6 to 8 minutes, or until the water has been absorbed and the couscous is tender. Fluff with a fork. Drizzle with olive oil and season with salt and pepper; stir to combine. Cover to keep warm. </li>
               <br>
               <li>While the couscous cooks, wash and dry the kale. Separate the kale leaves from the stems; discard the stems, then roughly chop the leaves. Peel and roughly chop 2 cloves of garlic. </li> 
               <br>
               <li>While the couscous continues to cook, in a large pan (nonstick, if you have one), heat a drizzle of olive oil on medium-high until hot. Add the chopped kale and half the chopped garlic; season with salt and pepper. Cook, stirring occasionally, 3 to 4 minutes, or until slightly wilted. Add 1/4 cup of water (carefully, as the liquid may splatter). Cook, stirring frequently, 2 to 3 minutes, or until the kale is wilted and the water has cooked off. Transfer to a bowl. Taste, then season with salt and pepper if desired. Cover with foil to keep warm. Wipe out the pan.  </li>
               <br>
               <li>Pat the beef dry with paper towels. Season with salt and pepper. In the same pan, heat a drizzle of olive oil on medium-high until hot. Add the seasoned beef in an even layer. Cook, without stirring, 1 to 2 minutes, or until lightly browned. Add half the dukkah (you will have extra) and the remaining chopped garlic. Cook, stirring frequently, 1 to 2 minutes, or until the beef is just cooked through. Turn off the heat. Stir in the crème fraîche. Taste, then season with salt and pepper if desired.</li>
               <br>
               <li>While the beef cooks, in a bowl, whisk together the tahini, vinegar, and 1 tablespoon of olive oil. Slowly whisk in up to 2 tablespoons of water to thin to your desired consistency. Taste, then season with salt and pepper if desired. Serve the cooked beef with the cooked couscous and kale. Top with the dressing. Enjoy!</li>
            </ol>
        </div>
    </div>
</div>